"""test

Revision ID: b68064ba06d1
Revises: 
Create Date: 2024-09-04 15:12:56.029702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68064ba06d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('ActivityId', sa.Integer(), nullable=False),
    sa.Column('ActivityName', sa.String(length=128), nullable=False),
    sa.Column('StartTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('EndTime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ActivityId')
    )
    op.create_table('Participant',
    sa.Column('ActivityId', sa.Integer(), nullable=False),
    sa.Column('ActivityName', sa.String(length=128), nullable=False),
    sa.Column('EndDate', sa.DateTime(), nullable=False),
    sa.Column('EmployeeId', sa.Integer(), nullable=False),
    sa.Column('TotalKm', sa.Integer(), nullable=False),
    sa.Column('TotalMinute', sa.Integer(), nullable=False),
    sa.Column('StravaId', sa.Integer(), nullable=False),
    sa.Column('Participant_Id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Participant_Id')
    )
    op.create_table('Token',
    sa.Column('EmployeeId', sa.Integer(), nullable=False),
    sa.Column('AccessToken', sa.String(length=128), nullable=False),
    sa.Column('Refreshtoken', sa.String(length=128), nullable=False),
    sa.Column('Token_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Token')
    op.drop_table('Participant')
    op.drop_table('Activity')
    # ### end Alembic commands ###
