<!-- Modal -->
<div class="modal fade" id="updateTimesheetModal" tabindex="-1" aria-labelledby="updateTimesheetModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="updateTimesheetModalLabel">19 Mon</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-between">
          <p>Enter new timesheet</p>
          <input type="text" class="form-control form-control-sm" id="numberInput" name="numberInput">
        </div>
        <p id="result" class="text-danger d-flex justify-content-center pt-3 pe-5"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#numberInput').on('input', function() {
      var inputValue = $(this).val();

      // Check if the input value is an integer
      if (Number.isInteger(parseFloat(inputValue)) || inputValue == '') {
        $('#result').text('');
      } else {
        $('#result').text('The input is not an integer.');
      }
    });
  });
</script>