<div class="border-right" id="sidebar-wrapper">
    <div class="bg-primary sidebar-heading text-white">HRM Dashboard</div>
    <div class="list-group list-group-flush">
        <a href="index.php?action=home" class="list-group-item list-group-item-action list-group-item-primary">Home</a>

        <?php if (json_decode($_SESSION["AuthUser"])->Role == 'Manager'): ?>
        <a 
            href="index.php?action=profile-management&page=1&pageSize=5" 
            class="list-group-item list-group-item-action list-group-item-primary"
        >
            Profile
        </a>
        <a href="index.php?action=timesheet-management" class="list-group-item list-group-item-action list-group-item-primary">Timesheet</a>
        <a href="index.php?action=activity-management" class="list-group-item list-group-item-action list-group-item-primary">Activity</a>
        <a href="index.php?action=point-management" class="list-group-item list-group-item-action list-group-item-primary">Point/Voucher</a>
        <?php endif ?>

        <?php if (json_decode($_SESSION["AuthUser"])->Role == 'Employee'): ?>
        <a 
            href="index.php?action=profile" 
            class="list-group-item list-group-item-action list-group-item-primary"
        >
            Profile
        </a>
        <!-- <a href="index.php?action=timesheet-management" class="list-group-item list-group-item-action list-group-item-primary">Timesheet</a>
        <a href="index.php?action=activity-management" class="list-group-item list-group-item-action list-group-item-primary">Activity</a>
        <a href="index.php?action=point-management" class="list-group-item list-group-item-action list-group-item-primary">Point/Voucher</a> -->
        <?php endif ?>
        
        <a href="index.php?action=tologin" class="list-group-item list-group-item-action list-group-item-primary">Logout</a>
    </div>
</div>