<div class="border-right" id="sidebar-wrapper">
    <div class="bg-primary sidebar-heading text-white">HRM Dashboard</div>
    <div class="list-group list-group-flush">
        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Home</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Profiles</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Activities</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Points</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Logout</a>
    </div>
</div>