<div class="border-right" id="sidebar-wrapper">
    <div class="bg-primary sidebar-heading text-white">HRM Dashboard</div>
    <div class="list-group list-group-flush">
        <a href="index.php?action=home" class="list-group-item list-group-item-action list-group-item-primary">Home</a>
        <a href="index.php?action=profile-management" class="list-group-item list-group-item-action list-group-item-primary">Profile</a>
        <a href="index.php?action=timesheet-management" class="list-group-item list-group-item-action list-group-item-primary">Timesheet</a>
        <a href="index.php?action=activity-management" class="list-group-item list-group-item-action list-group-item-primary">Activity</a>
        <a href="index.php?action=point-management" class="list-group-item list-group-item-action list-group-item-primary">Point/Voucher</a>
        
        <a href="index.php?action=tologin" class="list-group-item list-group-item-action list-group-item-primary">Logout</a>
    </div>
</div>