

<!-- Add Campaign Modal -->
<div class="modal fade" id="addCampaignModal" tabindex="-1" aria-labelledby="addCampaignModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addCampaignModalLabel">Add New Campaign</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- Modal content, e.g., form to add a new campaign -->
        <div class="rounded bg-secondary d-flex justify-content-center">
                    <img src="https://upload.wikimedia.org/wikipedia/en/a/a6/Pok%C3%A9mon_Pikachu_art.png" alt="avatar">
                </div>
                <form method="post" action=<?php echo 'index.php?action=create-activity'?>>
                    <div class="row">
                        <div class="col">
                            <div class="py-3">
                                <label for="activityName">Activity Name</label>
                                <input type="text" class="form-control" id="activityName" value="" name="activityName">
                            </div>
                            <div class="py-3">
                                <label for="startTime">Start Time</label>
                                <input type="datetime-local" class="form-control" id="startTime" value="" name="startTime">
                            </div>
                            <div class="py-3">
                                <label for="endTime">End Time</label>
                                <input type="datetime-local" class="form-control" id="endTime" value=""  name="endTime">
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-success">Create</button>
                    </div>
                </form>
      </div>
    </div>
  </div>
</div>
