<?php
    $ActivityName = empty($activity->ActivityName) ? : $activity->ActivityName ;
    $StartTime = empty((new DateTime($activity->StartTime))->format('Y-m-d H:i:s')) ?  :(new DateTime($activity->StartTime))->format('Y-m-d H:i:s');
    $EndTime = empty((new DateTime($activity->EndTime))->format('Y-m-d H:i:s')) ? : (new DateTime($activity->EndTime))->format('Y-m-d H:i:s');
?>
<!-- Update Activity Modal -->
<div class="modal fade" id=<?php echo 'editActivity'.$activity->ActivityId.'Modal'; ?> tabindex="-1" role="dialog" aria-labelledby=<?php echo 'editActivity'.$activity->ActivityId.'ModalLabel'; ?> aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id=<?php echo 'editActivity'.$activity->ActivityId.'ModalLabel'; ?>>Update Campaign</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="rounded bg-secondary d-flex justify-content-center">
                    <img src="https://upload.wikimedia.org/wikipedia/en/a/a6/Pok%C3%A9mon_Pikachu_art.png" alt="avatar">
                </div>
                <form method="post" action=<?php echo 'index.php?action=update-activity&activityId='.$activity->ActivityId ?>>
                    <div class="row">
                        <div class="col">
                            <div class="py-3">
                                <label for="activityName">Activity Name</label>
                                <input type="text" class="form-control" id="activityName" value="<?php echo $ActivityName; ?>" name="activityName">
                            </div>
                            <div class="py-3">
                                <label for="startTime">Start Time</label>
                                <input type="datetime-local" class="form-control" id="startTime" value="<?php echo $StartTime; ?>" name="startTime">
                            </div>
                            <div class="py-3">
                                <label for="endTime">End Time</label>
                                <input type="datetime-local" class="form-control" id="endTime" value="<?php echo $EndTime; ?>"  name="endTime">
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-success">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>