
<!-- Update Activity Modal -->
<div class="modal fade" id=<?php echo 'participateActivity'.$activity2->ActivityId.'Modal'; ?> tabindex="-1" role="dialog" aria-labelledby=<?php echo 'participateActivity'.$activity2->ActivityId.'ModalLabel'; ?> aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id=<?php echo 'participateActivity'.$activity2->ActivityId.'ModalLabel'; ?>>Join Campaign</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="rounded bg-secondary d-flex justify-content-center">
                    <img src="https://upload.wikimedia.org/wikipedia/en/a/a6/Pok%C3%A9mon_Pikachu_art.png" alt="avatar">
                </div>
                <form method="post" action=<?php echo 'index.php?action=update-activity&activityId='.$activity2->ActivityId ?>>
                    <div class="row">
                        <div class="col">
                            <div class="py-3">
                                <label for="stravaId">Strava ID</label>
                                <input type="text" class="form-control" id="activityName" value="" name="stravaId">
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-success">Join</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>