<div class="profile-management-nav-bar">
    <div class="container d-flex justify-content-end py-3">
        <a href="" class="mx-1 nav-link">Apply</a>
        <a href="" class="mx-1 nav-link active">Requests</a>
    </div>
</div>

<!-- Header Section -->
<header class="bg-light text-center py-5">
    <div class="container">
        <h1 class="display-4">Employee WFHs</h1>
        <p class="lead">View, add, edit, and manage profile information.</p>
    </div>
</header>

<!-- Employee Table Section -->
<section class="profile-management py-5">
    <div class="container">
        <div class="d-flex justify-content-between mb-4">
            <h2 class="mb-0">WFH Request List</h2>
        </div>

        <!-- Employee Table -->
        <div class="table-responsive">
            <table class="table table-bordered table-striped text-nowrap table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>Employee Name</th>
                        <th>Date</th>
                        <th>WFH Type</th>
                        <th>Notes</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($wfh_requests as $wfh_request): ?>
                    <tr>
                        <td><?php echo $wfh_request->Employee->EmployeeName?></td>
                        <td>
                            <?php echo $wfh_request->Date ?>
                        </td>
                        <td><?php echo $wfh_request->WfhType?></td>
                        <td><?php echo $wfh_request->Note?></td>
                        <td>
                            <?php if ($wfh_request->Status == 1): ?>
                                <a href = <?php echo 'index.php?action=deny-wfh&requestId='.$wfh_request->RequestId; ?> class="btn btn-secondary btn-sm" >
                                    Cancel
                                </a>
                            <?php else: ?>
                                <p class="text-success">Applied</p>
                            <?php endif ?>
                        </td>
                    </tr>
                    <?php endforeach?>
                </tbody>
            </table>
        </div>

        <?php
            $action_url = 'index.php?action=employee-wfh-request-management';
            require('./include/Paginationbar.phtml')
        ?>
    </div>
</section>