<?php
$isCheckIn = isset($checkInInfo);
?>

<div class="profile-management-nav-bar px-3">
    <div class="container d-flex justify-content-end py-3">
        <a href="index.php?action=profile" class="mx-1 nav-link">Profile</a>
        <a href="" class="mx-1 nav-link active">Attendance</a>
    </div>
</div>

<div class="container-fluid p-4">
    <?php if ($isCheckIn): ?>
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">Check In Information</h5>
                <div class="col-md-6 mt-3">
                    <div class="d-flex flex-row">
                        <i class="fas fa-calendar-alt p-1"></i>
                        <p class="fw-medium">&nbsp;Date:</p>
                        <p>&nbsp;<?php echo $checkInInfo->AttendanceDate ?></p>
                    </div>
                    <div class="d-flex flex-row">
                        <i class="fas fa-clock p-1"></i>
                        <p class="fw-medium">&nbsp;Time:</p>
                        <p>&nbsp;<?php echo $checkInInfo->CheckInTime ?></p>
                    </div>
                    <div class="d-flex flex-row">
                        <i class="bi bi-card-text px-1"></i>
                        <p class="fw-medium">&nbsp;Note:</p>
                        <p>&nbsp;<?php echo $checkInInfo->CheckInNote ?></p>
                    </div>
                </div>
            </div>
        </div>
    <?php endif ?>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><?php echo $isCheckIn ? 'Check Out' : 'Check In' ?></h5>
            <form method="post" action=<?php echo $isCheckIn ? 'index.php?action=check-out' : 'index.php?action=check-in' ?>>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="date" class="form-label">Date</label>
                            <div class="input-group">
                                <input 
                                    type="text" 
                                    class="form-control" 
                                    id="date" 
                                    placeholder=<?php echo date('d-m-Y') ?> 
                                    disabled 
                                    name=<?php echo $isCheckIn ? 'checkOutDate' : 'checkInDate' ?>
                                >
                                <span class="input-group-text">
                                    <i class="fas fa-calendar-alt"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="time" class="form-label">Time</label>
                            <div class="input-group">
                                <input
                                    type="text"
                                    class="form-control"
                                    id="time"
                                    placeholder=<?php 
                                        date_default_timezone_set('Asia/Ho_Chi_Minh');
                                        echo date('h:i:sa') 
                                    ?>
                                    disabled
                                    name=<?php echo $isCheckIn ? 'checkOutTime' : 'checkInTime' ?>
                                >
                                <span class="input-group-text">
                                    <i class="fas fa-clock"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="note" class="form-label">Note</label>
                    <textarea class="form-control" id="note" rows="3" placeholder="Type here" name=<?php echo $isCheckIn ? 'checkOutNote' : 'checkInNote' ?>></textarea>
                </div>

                <input type="text" name=employee value=<?php echo json_encode($attendance_employee)?> hidden>

                <div class="text-end">
                    <button type="submit" class="btn btn-success"><?php echo $isCheckIn ? 'Check Out' : 'Check In' ?></button>
                </div>
            </form>
        </div>
    </div>
</div>