<!-- Add Employee Modal -->
<div class="modal fade" id="deactivateEmployeeModal" tabindex="-1" role="dialog" aria-labelledby="deactivateEmployeeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deactivateEmployeeModalLabel">Do you want to deactivate this employee ?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <p>This account will be deactivated and can only be re-activated by admin</p>
            </div>

            <div class="modal-footer">
                <a href=<?php echo 'index.php?action=deactivate-profile&employeeId='.$profile->EmployeeId ?> type="button" class="btn btn-primary">Yes</a>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>