<!-- Add Employee Modal -->
<div class="modal fade" id="addEmployeeModal" tabindex="-1" role="dialog" aria-labelledby="addEmployeeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addEmployeeModalLabel">Employee: </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="rounded bg-secondary">
                    <img src="" alt="avatar">
                </div>

                <form>
                    <div class="row">
                        <div class="col">
                            <div class="py-3">
                                <label for="firstName">First Name</label>
                                <input type="text" class="form-control" id="firstName">
                            </div>
                            <div class="py-3">
                                <label for="middleName">Middle Name</label>
                                <input type="text" class="form-control" id="middleName">
                            </div>
                            <div class="py-3">
                                <label for="lastName">Last Name</label>
                                <input type="text" class="form-control" id="lastName">
                            </div>
                            <div class="py-3">
                                <label for="idCardNum">Id Card Number</label>
                                <input type="text" class="form-control" id="idCardNum">
                            </div>
                            <div class="py-3">
                                <label for="taxNum">Tax Number</label>
                                <input type="text" class="form-control" id="taxNum">
                            </div>
                        </div>

                        <div class="col">
                            <div class="py-3">
                                <label for="address">Address</label>
                                <input type="text" class="form-control" id="address">
                            </div>
                            <div class="py-3">
                                <label for="phoneNum">Phone Number</label>
                                <input type="text" class="form-control" id="phoneNum">
                            </div>
                            <div class="py-3">
                                <label for="bankAccount">Bank Account</label>
                                <input type="text" class="form-control" id="bankAccount">
                            </div>
                            <div class="py-3">
                                <label for="jobTitle">Job Title</label>
                                <input type="text" class="form-control" id="jobTitle">
                            </div>
                            <div class="py-3">
                                <label for="gender">Gender</label>
                                <input type="text" class="form-control" id="gender">
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>