<!-- Navigation Bar -->
<div class="profile-management-nav-bar">
    <div class="container d-flex justify-content-end py-3">
        <a href="index.php?action=profile-management&page=1&pageSize=5" class="mx-1 nav-link active">Profile</a>
        <div class="dropdown mx-1">
            <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Leave
            </a>
            <ul class="dropdown-menu" aria-labelledby="leaveDropdown">
                <li><a class="dropdown-item" href="index.php?action=leave-management&page=1&pageSize=5">My Leave</a></li>
                <li><a class="dropdown-item" href="index.php?action=leave-request-management&page=1&pageSize=5">Leave Request</a></li>
            </ul>
        </div>

        <div class="dropdown mx-1">
            <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                WFH
            </a>
            <ul class="dropdown-menu" aria-labelledby="wfhDropdown">
                <li><a class="dropdown-item" href="index.php?action=wfh-management&page=1&pageSize=5">My WFH</a></li>
                <li><a class="dropdown-item" href="index.php?action=wfh-request-management&page=1&pageSize=5">WFH Request</a></li>
            </ul>
        </div>
    </div>
</div>

<!-- Header Section -->
<header class="bg-light text-center py-5">
    <div class="container">
        <h1 class="display-4">Employee Management</h1>
        <p class="lead">View, add, edit, and manage profile information.</p>
    </div>
</header>

<!-- Employee Table Section -->
<section class="profile-management py-5">
    <div class="container">
        <div class="d-flex justify-content-between mb-4">
            <h2 class="mb-0">Employee List</h2>
        </div>

        <!-- Search -->
        <div class="container py-4">
            <div class="row border rounded rounded-4 p-3">
                <div class="col">
                    <div>
                        <p class="fs-6 fw-medium">Employee Name</p>
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    </div>
                </div>
                <div class="col">
                    <div>
                        <p class="fs-6 fw-medium">Id Number</p>
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    </div>
                </div>
                <div class="col">
                    <div>
                        <p class="fs-6 fw-medium">Job Title</p>
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    </div>
                </div>
            </div>

            <div class="container d-flex justify-content-end py-3">
                <button class="btn btn-primary">Search</button>
            </div>
        </div>

        <!-- Employee Table -->
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>First Name</th>
                        <th>Middle Name</th>
                        <th>Last Name</th>
                        <th>ID Number</th>
                        <th>Job Title</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($profiles as $profile): ?>
                        <?php
                        require("./view/ProfileManagement/EditProfileModal.phtml");
                        require("./view/ProfileManagement/ConfirmDeactivateModal.phtml");
                        ?>

                        <tr>
                            <td><?php echo $profile->FirstName ?></td>
                            <td><?php echo $profile->MiddleName ?></td>
                            <td><?php echo $profile->LastName ?></td>
                            <td><?php echo $profile->IdCardNum ?></td>
                            <td><?php echo $profile->JobTitle ?></td>

                            <td>
                                <button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target=<?php echo '#editProfile' . $profile->EmployeeId . 'Modal'; ?>>
                                    <i class="bi bi-pencil-square"></i>
                                </button>
                                <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deactivateEmployeeModal">
                                    <i class="bi bi-archive"></i>
                                </button>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>

        <?php
            $action_url = 'index.php?action=profile-management';
            require('./include/Paginationbar.phtml')
        ?>
    </div>
</section>